name: shikensu
version: 0.4.0
maintainer: Steven Vandevelde <icid.asset@gmail.com>
category: Filesystem


synopsis: Run a sequence of functions on in-memory representations of files
description: See README at <https://github.com/icidasset/shikensu#readme>
license: MIT
github: icidasset/shikensu


default-extensions:
   DisambiguateRecordFields
   DuplicateRecordFields
   OverloadedStrings


dependencies:
  - aeson == 2.*
  - base >= 4.9 && < 5
  - bytestring >= 0.10 && < 0.12
  - directory == 1.*
  - filepath == 1.*
  - flow == 1.*
  - Glob >= 0.7 && < 1
  - unordered-containers == 0.2.*
  - text == 1.*


extra-source-files:
  - "*.md"
  - "tests/fixtures/example.md"


library:
  source-dirs: src


tests:
  spec:
    main: Test.hs
    source-dirs:
      - tests
      - src
    dependencies:
      - tasty == 1.*
      - tasty-hunit == 0.*
